"""add data_subjects and retention_policies tables

Revision ID: ce8dbfe4f026
Revises: 26072cb1fed2
Create Date: 2026-04-01 10:32:03.493723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce8dbfe4f026'
down_revision: Union[str, Sequence[str], None] = '26072cb1fed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_subjects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('original_id', sa.String(length=256), nullable=False),
    sa.Column('pseudonym', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('erasure_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('erasure_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('erasure_status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pseudonym')
    )
    op.create_index('ix_data_subjects_pseudonym', 'data_subjects', ['pseudonym'], unique=False)
    op.create_index('ix_data_subjects_tenant', 'data_subjects', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_data_subjects_tenant_id'), 'data_subjects', ['tenant_id'], unique=False)
    op.create_table('retention_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('audit_retention_days', sa.Integer(), nullable=False),
    sa.Column('pii_retention_days', sa.Integer(), nullable=False),
    sa.Column('auto_purge_enabled', sa.Boolean(), nullable=False),
    sa.Column('policy_version', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retention_policies')
    op.drop_index(op.f('ix_data_subjects_tenant_id'), table_name='data_subjects')
    op.drop_index('ix_data_subjects_tenant', table_name='data_subjects')
    op.drop_index('ix_data_subjects_pseudonym', table_name='data_subjects')
    op.drop_table('data_subjects')
    # ### end Alembic commands ###
