"""add data_subjects and retention_policies tables

Revision ID: d121edd2b54e
Revises: ce8dbfe4f026
Create Date: 2026-04-01 10:40:07.959812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd121edd2b54e'
down_revision: Union[str, Sequence[str], None] = 'ce8dbfe4f026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
